### ISSUE TITLE
libtiff.so issue 

### ISSUE THREAD

**Issue by botteon** [garciafederico/pyXspecExplorer#1]
Hi,

nice tool! I am trying to make it running on ubuntu 24.04, with heasoft-6-34 and in a conda environment with python 3.11. Running the main.py script returns

`ImportError: libtiff.so.5: cannot open shared object file: No such file or directory`

In Ubuntu, installing libtiff6 and/or libtiff5-dev does not solve the issue. I temporary solved it by installing libtiff6 and making a symbolic link

`ln -s /usr/lib/x86_64-linux-gnu/libtiff.so.6 /usr/lib/x86_64-linux-gnu/libtiff.so.5`

but this is quite hardcoded. Probably this is an incompatibility with the newest ubuntu version?

In any case, running  main.py now the output is

```
Models will now use energy array created from:
   0.05 - 500   5000 log bins


========================================================================
Model bbodyrad<1> + nthComp<2> Source No.: 1   Active/Off
Model Model Component  Parameter  Unit     Value
 par  comp
   1    1   bbodyrad   kT         keV      3.00000      +/-  0.0          
   2    1   bbodyrad   norm                1.00000      +/-  0.0          
   3    2   nthComp    Gamma               1.70000      +/-  0.0          
   4    2   nthComp    kT_e       keV      100.000      +/-  0.0          
   5    2   nthComp    kT_bb      keV      0.100000     frozen
   6    2   nthComp    inp_type   0/1      0.0          frozen
   7    2   nthComp    Redshift            0.0          frozen
   8    2   nthComp    norm                1.00000      +/-  0.0          
________________________________________________________________________

Traceback (most recent call last):
  File "/opt/Software/pyXspecExplorer/main.py", line 147, in <module>
    sliders.append(Sliderlog(plt_sliders[-1],
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/test_env/lib/python3.11/site-packages/matplotlib/widgets.py", line 497, in __init__
    self.set_val(valinit)
  File "/opt/Software/pyXspecExplorer/main.py", line 22, in set_val
    xy[2] = val, 1
    ~~^^^
TypeError: 'tuple' object does not support item assignment

```

which suggests an incompatibility with new python/python packages (?)

**Comment by garciafederico** [comment]
Thanks for the feedback! Indeed looks like the SliderLog tricks I was using became deprecated for newer versions of matplotlib. I have rewritten the logarithmic sliders in main.py in a simpler fashion. It should work fine now!  Let me know if that helps.

**Comment by botteon** [comment]
It works! Thanks!
